# Matrix Invers

Invers matriks adalah kebalikan (invers) dari sebuah matriks yang apabila matriks tersebut dikalikan dengan inversnya, akan menjadi matriks identitas. Invers matriks dilambangkan dengan A-1. Suatu matriks dikatakan memiliki invers jika determinan dari matriks tersebut tidak sama dengan nol(non-singular).

Invers suatu matriks hanya mungkin terjadi jika sifat-sifat berikut berlaku:
1. Matriksnya harus berupa matriks persegi.
2. Matriksnya harus berupa matriks non-singular
3. Terdapat matriks Identitas I yang mana $A A^{-1} = A^{-1} A = I$

## Mencari Matrix Invers Menggunakan Metode Eliminasi Gauss-Jordan

Metode Gauss-Jordan merupakan salah satu varian dari eliminasi Gaussian yang dilakukan dengan cara operasi reduksi baris untuk mencari invers suatu matriks.

Langkah-langkah Mencari Invers Suatu Matriks Menggunakan Metode Eliminasi Gauss-Jordan

1. diberikan sebuah matrix $A_{3*3}$

\begin{bmatrix}
1 & 2 & -2\\ 
1 & 1 & 1\\ 
0 & 0 & 1
\end{bmatrix}
    
2. Bentuklah matriks yang diperbesar dengan matriks identitas $AI$.

\begin{bmatrix}
1 & 2 & -2 & 1 & 0 & 0\\ 
1 & 1 & 1 & 0 & 1 & 0\\ 
0 & 0 & 1 & 0 & 0 & 1
\end{bmatrix}
3. Lakukan operasi reduksi baris pada matriks yang diperbesar ini untuk menghasilkan bentuk $ IA^{-1}$

In [1]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
AI = np.array([[1,2,-2,1,0,0],[1,1,1,0,1,0],[0,0,1,0,0,1]])
print(AI,"\n")

AI1 = RowAdd(AI,0,1,-1)
print(AI1,"\n")

AI2 = RowScale(AI1,1,-1)
print(AI2,"\n")

AI3 = RowAdd(AI2,1,0,-2)
print(AI3,"\n")

AI4 = RowAdd(AI3,2,1,3)
print(AI4,"\n")

AI5 = RowAdd(AI4,2,0,-4)
print(AI5,"\n")

[[ 1  2 -2  1  0  0]
 [ 1  1  1  0  1  0]
 [ 0  0  1  0  0  1]] 

[[ 1.  2. -2.  1.  0.  0.]
 [ 0. -1.  3. -1.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  2. -2.  1.  0.  0.]
 [-0.  1. -3.  1. -1. -0.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  0.  4. -1.  2.  0.]
 [-0.  1. -3.  1. -1. -0.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  0.  4. -1.  2.  0.]
 [ 0.  1.  0.  1. -1.  3.]
 [ 0.  0.  1.  0.  0.  1.]] 

[[ 1.  0.  0. -1.  2. -4.]
 [ 0.  1.  0.  1. -1.  3.]
 [ 0.  0.  1.  0.  0.  1.]] 



4. dari operasi di atas di dapat $IA^{-1} $
\begin{bmatrix}
1 & 0 & 0 &-1 & 2 & -4\\ 
0 & 1 & 0 & 1 & -1 & 3\\ 
0 & 0 & 1 & 0 & 0 & 1
\end{bmatrix}

maka $ A^{-1} $

\begin{bmatrix}
-1 & 2 & -4\\ 
1 & -1 & 3\\ 
0 & 0 & 1
\end{bmatrix}

5. cek apakah $AA^{-1}=I$

In [3]:
A = np.array([[1,2,-2],[1,1,1],[0,0,1]])
AI6 = np.array([[-1,2,-4],[1,-1,3],[0,0,1]])
A_I = np.dot(A,AI6)
print(A_I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
print(np.linalg.inv(A))

[[-1.  2. -4.]
 [ 1. -1.  3.]
 [ 0.  0.  1.]]
