In [1]:
import numpy as np
A = np.array([[2,1],[1,1]])
I = np.array([[1,0],[0,1]])

B = A * I
C = I * A

print(B)
print(C)


[[2 0]
 [0 1]]
[[2 0]
 [0 1]]


In [2]:
x1 = 3
x2 = 1
x3 = 1

A = 2*x1 + 2*x2 + x3
B = 2*x1 + 2*x2 + x3
C = 2*x1 + 2*x2 + x3



In [3]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [4]:
import numpy as np
A=np.array([[2,2,1],[4,2,3],[1,3,-1]])
print(A)
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(I)

[[ 2  2  1]
 [ 4  2  3]
 [ 1  3 -1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:

A2 = RowAdd(A,0,1,-2)
print(A2)
print()
I2 = RowAdd(I,0,1,-2)
print(I2)

[[ 2.  2.  1.]
 [ 0. -2.  1.]
 [ 1.  3. -1.]]

[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
A3 = RowAdd(A2,0,2,-1/2)
print(A3)
print()
I3 = RowAdd(I2,0,2,-1/2)
print(I3)

[[ 2.   2.   1. ]
 [ 0.  -2.   1. ]
 [ 0.   2.  -1.5]]

[[ 1.   0.   0. ]
 [-2.   1.   0. ]
 [-0.5  0.   1. ]]


In [7]:
A4 = RowAdd(A3,1,2,1)
print(A4)
print()
I4 = RowAdd(I3,1,2,1)
print(I4)

[[ 2.   2.   1. ]
 [ 0.  -2.   1. ]
 [ 0.   0.  -0.5]]

[[ 1.   0.   0. ]
 [-2.   1.   0. ]
 [-2.5  1.   1. ]]


In [8]:
A5 = RowScale(A4,0,1/2)
print(A5)
print()
I5 = RowScale(I4,0,1/2)
print(I5)

[[ 1.   1.   0.5]
 [ 0.  -2.   1. ]
 [ 0.   0.  -0.5]]

[[ 0.5  0.   0. ]
 [-2.   1.   0. ]
 [-2.5  1.   1. ]]


In [9]:
A6 = RowScale(A5,1,-1/2)
print(A6)
print()
I6 = RowScale(I5,1,-1/2)
print(I6)

[[ 1.   1.   0.5]
 [-0.   1.  -0.5]
 [ 0.   0.  -0.5]]

[[ 0.5  0.   0. ]
 [ 1.  -0.5 -0. ]
 [-2.5  1.   1. ]]


In [10]:
A7 = RowScale(A6,2,-2)
print(A7)
print()
I7 = RowScale(I6,2,-2)
print(I7)

[[ 1.   1.   0.5]
 [-0.   1.  -0.5]
 [-0.  -0.   1. ]]

[[ 0.5  0.   0. ]
 [ 1.  -0.5 -0. ]
 [ 5.  -2.  -2. ]]


In [11]:
A8 = RowAdd(A7,2,1,1/2)
print(A8)
print()
I8 = RowAdd(I7,2,1,1/2)
print(I7)

[[ 1.   1.   0.5]
 [-0.   1.   0. ]
 [-0.  -0.   1. ]]

[[ 0.5  0.   0. ]
 [ 1.  -0.5 -0. ]
 [ 5.  -2.  -2. ]]


In [12]:
A9 = RowAdd(A8,2,0,-1/2)
print(A9)
print()
I9 = RowAdd(I8,2,0,-1/2)
print(I9)

[[ 1.  1.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]

[[-2.   1.   1. ]
 [ 3.5 -1.5 -1. ]
 [ 5.  -2.  -2. ]]


In [13]:
A10 = RowAdd(A9,1,0,-1)
print(A10)
print()
I10 = RowAdd(I9,1,0,-1)
print(I10)

[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]

[[-5.5  2.5  2. ]
 [ 3.5 -1.5 -1. ]
 [ 5.  -2.  -2. ]]


In [14]:
import numpy as np
b = np.array([[9],[17],[5]])
print(b)

[[ 9]
 [17]
 [ 5]]


In [15]:
hasil = I10 @ b
print(hasil)

[[3.]
 [1.]
 [1.]]
