# Materi dan Tugas Pertemuan 3

##  Menghitung Matrix dengan Program

### Cara Membuat Matrix Secara Manual Menggunakan Program Python



1. Memanggil library numpy menggunakan syntax [import numpy] import. fungsinya untuk memanggil file lain dalam satu modul karena numpy adalah sebuah library yang bisa di panggil

2. Membuat matrix secara manual menggunakan syntax "numpy.array", misal : [ A = numpy.array([[1,3,4],[-2,-8,-5]]) ], dengan isi numpy.array numpy adalah library yang sudah dipanggil tadi, dan array kegunaannya untuk memudahkan operasi komputasi tipe data numerik seperti penjumlahan, pengurangan, perkalian, pangkat, dan operasi lainnya yang bisa diterapkan pada vektor atau matrix dan beri angka untuk kolom dan baris pada matrix

In [1]:
import numpy

A = numpy.array([[1,3,4],[-2,-8,-5]])
print(A)

[[ 1  3  4]
 [-2 -8 -5]]


### Cara Menentukan Matrix Secara Random Menggunakan Program Python
1. Memanggil numpy dan random menggunakan syntax [import numpy] & [import Random] import gunanya untuk kita memanggil file lain dalam satu modul, numpy dan random adalah sebuah library yang bisa di panggil

2. Membuat matrix menggunakan syntax "numpy.random.randint" misalnya : [ “A = numpy.random.randint(10, size=(2,2))” ], disini kegunaan dari randint sendiri adalah untuk mengacak angka, dan 10 adalah batas dari acak angka randint, size=(2,2) adalah ukuran kolom baris sebuah matrix

In [2]:
import numpy as np
import random

A = np.random.randint(10,size=(2,2))
print(A)

[[4 3]
 [2 8]]


### Cara Mengubah Matrix Menjadi Matrix Transpose Menggunakan Program Python

Menentukan Matrix mana yang ingin di transpose, dan beri syntax [A.transpose()] Syntax “transpose()” digunakan untuk menghasilkan transpos dari matriks A. Transpos suatu matriks adalah operasi yang mengubah baris matriks menjadi kolom dan sebaliknya. Dengan kata lain, elemen pada baris ke-i dan kolom ke-j dari matriks asli akan menjadi elemen pada baris ke-j dan kolom ke-i dalam matriks transpose

In [3]:
import numpy as np
import random

A = np.random.randint(10,size=(2,2))
A_T = A.transpose()
print("Matrix A")
print(A)
print("Matrix A yang sudah di transpose")
print(A_T)


Matrix A
[[8 4]
 [2 8]]
Matrix A yang sudah di transpose
[[8 2]
 [4 8]]


### Cara Mengetahui Shape Matrix Menggunakan Program Python

Menentukan variable matrix mana yang ingin di ketahui shape nya, dan tambahkan syntax [A.Shape] Shape digunakan untuk mendapatkan tuple yang menyatakan dimensi dari array/matriks A. Dalam konteks NumPy atau library lain yang mendukung atribut shape, A.shape memberikan informasi tentang jumlah baris dan kolom

In [4]:
import numpy as np
import random

A = np.random.randint(10,size=(4,4))
A.shape

(4, 4)

# TUGAS PERTEMUAN 3

Mengalikan Matrix Menggunakan Python

In [5]:
import numpy as np

A = np.random.randint(10, size=(4, 3))
B = np.random.randint(10, size=(3, 4))



Kumpulan_matrix = [A, B]

hasil = Kumpulan_matrix[0]

for matrix in Kumpulan_matrix[1:]:
    hasil = np.dot(hasil, matrix)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nHasil akhir perkalian matriks:")
print(hasil)

Matrix A:
[[5 0 4]
 [3 1 9]
 [0 8 5]
 [3 8 7]]

Matrix B:
[[3 7 0 9]
 [3 9 0 7]
 [2 7 9 2]]

Hasil akhir perkalian matriks:
[[ 23  63  36  53]
 [ 30  93  81  52]
 [ 34 107  45  66]
 [ 47 142  63  97]]
