# Aljabar Matrix

##  Menghitung Matrix dengan Program

### Cara Membuat Matrix Secara Manual Menggunakan Program Python



1. Memanggil library numpy menggunakan syntax [import numpy] import. fungsinya untuk memanggil file lain dalam satu modul karena numpy adalah sebuah library yang bisa di panggil

2. Membuat matrix secara manual menggunakan syntax "numpy.array", misal : [ A = numpy.array([[1,3,4],[-2,-8,-5]]) ], dengan isi numpy.array numpy adalah library yang sudah dipanggil tadi, dan array kegunaannya untuk memudahkan operasi komputasi tipe data numerik seperti penjumlahan, pengurangan, perkalian, pangkat, dan operasi lainnya yang bisa diterapkan pada vektor atau matrix dan beri angka untuk kolom dan baris pada matrix

In [1]:
import numpy

A = numpy.array([[1,3,4],[-2,-8,-5]])
print(A)

[[ 1  3  4]
 [-2 -8 -5]]


### Cara Menentukan Matrix Secara Random Menggunakan Program Python
1. Memanggil numpy dan random menggunakan syntax [import numpy] & [import Random] import gunanya untuk kita memanggil file lain dalam satu modul, numpy dan random adalah sebuah library yang bisa di panggil

2. Membuat matrix menggunakan syntax "numpy.random.randint" misalnya : [ “A = numpy.random.randint(10, size=(2,2))” ], disini kegunaan dari randint sendiri adalah untuk mengacak angka, dan 10 adalah batas dari acak angka randint, size=(2,2) adalah ukuran kolom baris sebuah matrix

In [2]:
import numpy as np
import random

A = np.random.randint(10,size=(2,2))
print(A)

[[8 5]
 [5 6]]


### Cara Mengubah Matrix Menjadi Matrix Transpose Menggunakan Program Python

Menentukan Matrix mana yang ingin di transpose, dan beri syntax [A.transpose()] Syntax “transpose()” digunakan untuk menghasilkan transpos dari matriks A. Transpos suatu matriks adalah operasi yang mengubah baris matriks menjadi kolom dan sebaliknya. Dengan kata lain, elemen pada baris ke-i dan kolom ke-j dari matriks asli akan menjadi elemen pada baris ke-j dan kolom ke-i dalam matriks transpose

In [3]:
import numpy as np
import random

A = np.random.randint(10,size=(2,2))
A_T = A.transpose()
print("Matrix A")
print(A)
print("Matrix A yang sudah di transpose")
print(A_T)


Matrix A
[[1 5]
 [9 3]]
Matrix A yang sudah di transpose
[[1 9]
 [5 3]]


### Cara Mengetahui Shape Matrix Menggunakan Program Python

Menentukan variable matrix mana yang ingin di ketahui shape nya, dan tambahkan syntax [A.Shape] Shape digunakan untuk mendapatkan tuple yang menyatakan dimensi dari array/matriks A. Dalam konteks NumPy atau library lain yang mendukung atribut shape, A.shape memberikan informasi tentang jumlah baris dan kolom

In [4]:
import numpy as np
import random

A = np.random.randint(10,size=(4,4))
A.shape

(4, 4)

## Operasi pada Matriks

Operasi matriks adalah operasi yang dilakukan terhadap dua atau lebih matriks. Ini juga dikenal sebagai operasi aljabar matriks. Terdapat tiga jenis operasi matriks yang umum dilakukan:

### Penjumlahan

Penjumlahan matriks mirip dengan penjumlahan pada bilangan. Syarat utama untuk penjumlahan matriks adalah matriks yang dijumlahkan harus memiliki ordo yang sama. Misalnya, matriks A dengan ordo 2 x 2 hanya dapat dijumlahkan dengan matriks lain yang juga memiliki ordo 2 x 2.

Contoh :

In [5]:
import numpy as np
import random

A = np.random.randint(10,size=(2,2))
B = np.random.randint(10,size=(2,2))

print("Matriks A")
print(A)
print()
print("Matriks B")
print(B)
print()

AB = A + B
print("Hasil dari A + B")
print(AB)

Matriks A
[[3 5]
 [2 9]]

Matriks B
[[7 4]
 [5 6]]

Hasil dari A + B
[[10  9]
 [ 7 15]]


### Pengurangan

Konsep pengurangan matriks mirip dengan penjumlahan. Syaratnya tetap sama, yaitu matriks yang dikurangkan harus memiliki ordo yang sama.

Contoh:

In [6]:
import numpy as np
import random

A = np.random.randint(10,size=(2,2))
B = np.random.randint(10,size=(2,2))

print("Matriks A")
print(A)
print()
print("Matriks B")
print(B)
print()

AB = A - B
print("Hasil dari A - B")
print(AB)

Matriks A
[[2 9]
 [9 6]]

Matriks B
[[4 9]
 [9 2]]

Hasil dari A - B
[[-2  0]
 [ 0  4]]


### Perkalian

Perkalian matriks melibatkan operasi antara elemen-elemen matriks. Perkalian matriks bersifat TIDAK komutatif, artinya A × B tidak selalu sama dengan B × A. Perkalian matriks memerlukan aturan tertentu, seperti jumlah kolom matriks pertama harus sama dengan jumlah baris matriks kedua.

contoh:

In [7]:
import numpy as np
import random

A = np.random.randint(10,size=(3,3))
B = np.random.randint(10,size=(3,3))

print("Matriks A")
print(A)
print()
print("Matriks B")
print(B)
print()

# Perkalian matriks dengan matriks lain
AB = A * B
print("Hasil dari A x B")
print(AB)
print()

# Perkalian matriks dengan konstanta
k = 2
Ak = A * k
print("Hasil dari A x k")
print(Ak)


Matriks A
[[5 8 4]
 [6 4 4]
 [5 8 2]]

Matriks B
[[9 3 2]
 [4 5 4]
 [6 5 7]]

Hasil dari A x B
[[45 24  8]
 [24 20 16]
 [30 40 14]]

Hasil dari A x k
[[10 16  8]
 [12  8  8]
 [10 16  4]]


## Tugas Pertemuan 3
Mengalikan Matrix Menggunakan Perulangan

In [8]:
import numpy as np

A = np.random.randint(10, size=(4, 3))
B = np.random.randint(10, size=(3, 4))



Kumpulan_matrix = [A, B]

hasil = Kumpulan_matrix[0]

for matrix in Kumpulan_matrix[1:]:
    hasil = np.dot(hasil, matrix)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nHasil akhir perkalian matriks:")
print(hasil)

Matrix A:
[[7 3 0]
 [5 0 2]
 [7 8 1]
 [1 1 1]]

Matrix B:
[[2 6 7 4]
 [1 9 0 3]
 [2 3 7 4]]

Hasil akhir perkalian matriks:
[[ 17  69  49  37]
 [ 14  36  49  28]
 [ 24 117  56  56]
 [  5  18  14  11]]
