# Aljabar Matriks

In [10]:
import numpy as np
A = np.array ([[1,3,5],[2,1,8],[3,6,2]])
B = np.array ([[3,9,5],[4,8,7],[4,7,6]])
C = np.array ([[3,7],[4,8],[3,4]])
D = np.array ([[4,3,6],[6,5,7],[4,2,7]])

E = np.random.randint(10,size=(3,3))
print(D,"\n")

c = 2
d = 4
e = c + d
G = e * A
print(G,"\n")

H = (c * A) + (d * A)
print(H,"\n")

K = A + B
print(K,"\n")

L = C.shape[0]
print(L,"\n")

M = C.shape
print(M,"\n")

F = A @ C
print(F,"\n")

A_T = A.transpose()
COV = A * A_T
print(A,"\n")
print(COV,"\n")

N = np.array ([[1,2,3],[2,4,5],[3,5,6]])
N_T = N.transpose()
B = N - N_T
print(B,"\n")

O = (A + B) * D
O_T = O.transpose()
print(O_T, "\n")


[[4 3 6]
 [6 5 7]
 [4 2 7]] 

[[ 6 18 30]
 [12  6 48]
 [18 36 12]] 

[[ 6 18 30]
 [12  6 48]
 [18 36 12]] 

[[ 4 12 10]
 [ 6  9 15]
 [ 7 13  8]] 

3 

(3, 2) 

[[30 51]
 [34 54]
 [39 77]] 

[[1 3 5]
 [2 1 8]
 [3 6 2]] 

[[ 1  6 15]
 [ 6  1 48]
 [15 48  4]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[ 4 12 12]
 [ 9  5 12]
 [30 56 14]] 

