# Materi dan Tugas Pertemuan 2

Menggambar Bidang 3 Dimensi
Eliminasi Gauss adalah algoritma yang digunakan untuk menyelesaikan sistem persamaan linear. Algoritma ini terdiri dari serangkaian operasi yang dilakukan pada matriks koefisien dari sistem persamaan tersebut.

Ada tiga jenis operasi baris dasar yang dapat dilakukan pada baris matriks tersebut:

1. Menukar posisi dua baris.

2. Mengalikan suatu baris dengan skalar bukan nol .

3. Menambahkan suatu baris dengan suatu kelipatan dari baris yang lain.

Operasi-operasi ini tidak mengubah kumpulan solusi. Oleh karena itu, jika tujuan seseorang adalah untuk menyelesaikan sistem persamaan linear, penggunaan operasi baris ini dapat membuat masalah menjadi lebih mudah

## Penyelesaian Sistem Linier

In [1]:
## Contoh penggunaan eliminasi gaussian pada bahasa pemrograman python

# import library numpy

import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


In [15]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [17]:
# tukar posisi baris 1 dan baris 2

A1 = RowSwap(A,0,1)
print(A1)

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]]


In [21]:
# baris 1 di kali -8 lalu ditambahkan ke baris 2
A2 = RowAdd(A1,0,1,-8)
print(A2)

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  2.   1.   1.   5.]]


In [22]:
# baris 1 di kali -2 lalu ditambahkan ke baris 3
A3 = RowAdd(A2,0,2,-2)
print(A3)

[[  1.   2.   3.   9.]
 [  0.  -7. -23. -53.]
 [  0.  -3.  -5. -13.]]


In [23]:
# baris 2 di kalikan dengan -1/7
A4 = RowScale(A3,1,-1/7)
print(A4)

[[  1.           2.           3.           9.        ]
 [ -0.           1.           3.28571429   7.57142857]
 [  0.          -3.          -5.         -13.        ]]


In [24]:
# baris 2 di kalikan 3 lalu ditambahkan ke baris 3
A5 = RowAdd(A4,1,2,3)
print(A5)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          4.85714286  9.71428571]]


In [26]:
# baris 3 di  kalikan dengan 1/4.85714286
A6 = RowScale(A5,2,1/4.85714286)
print(A6)

[[ 1.          2.          3.          9.        ]
 [-0.          1.          3.28571429  7.57142857]
 [ 0.          0.          1.          2.        ]]


persamaannya adalah :

$$
x_1+2x_2+3x_3=9\\
x_2+3.28571429x_3=7.57142857\\
x_3=2\\
$$


In [38]:
x3 = 2
print('x3 =',x3)
x2 = 7.57142857 - (3.28571429*x3)
print('x2 =',round(x2))
x1 = 9 - 2*x2 - 3*x3
print('x1 =',round(x1))

x3 = 2
x2 = 1
x1 = 1


Hasil dari sistem persamaan berikut adalah:
$$
8x_1 + 9x_2 + x_3 = 19\\
x_1  + 2x_2 + 3x_3 = 9\\
2x_1 + x_2  + x_3 = 5\\
$$

Hasil setelah dibulatkan :
$$
x_1 + 2x_2 + 3x_3 = 9\\
x_2 + 3x_3 = 8\\
x_3 = 2\\
$$